port 1194
proto udp
dev tun0

user nobody
group nogroup
persist-key
persist-tun

topology subnet
server 10.8.0.0 255.255.255.0

# Only push the routes you actually need to reach in your private cloud
push "route 10.20.0.0 255.255.0.0"
push "dhcp-option DNS 10.20.0.10"

# PKI
ca /etc/openvpn/pki/easyrsa/ca.crt
cert /etc/openvpn/pki/easyrsa/issued/server.crt
key /etc/openvpn/pki/easyrsa/private/server.key
dh none
#ecdh-curve prime256v1
tls-groups prime256v1:X25519:secp384r1
tls-crypt /etc/openvpn/pki/tls-crypt.key

# TLS and crypto hardening
verify-client-cert require
remote-cert-tls client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384:TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384
auth SHA256
data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305
data-ciphers-fallback AES-256-GCM
cipher AES-256-GCM

# Security
keepalive 10 120
explicit-exit-notify 1
#duplicate-cn 0
client-config-dir /etc/openvpn/ccd
ccd-exclusive
ifconfig-pool-persist /etc/openvpn/server/ipp.txt
status /etc/openvpn/server/status.log
verb 3

# Compression should stay off
allow-compression no

